services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
    container_name: back-end
    expose:
      - "5252"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/var/www/html
    container_name: front-end
    expose:
      - "9000"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-image
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
